<a href="https://colab.research.google.com/github/pankaj646/Todo_List/blob/master/plotly_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objects as go

In [ ]:
matches=pd.read_csv("/content/matches.csv")
delivery=pd.read_csv("/content/deliveries.csv")

In [ ]:
ipl=delivery.merge(matches,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0.0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0.0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0.0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0.0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0.0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [ ]:
top50=ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()

In [ ]:
new_ipl=ipl[ipl['batsman'].isin(top50)]

In [ ]:
runs=new_ipl.groupby('batsman')['batsman_runs'].sum()
balls=new_ipl.groupby('batsman')['batsman_runs'].count()

sr=(runs/balls)*100
sr=sr.reset_index()
sr

             batsman  batsman_runs
0          A Symonds    124.711908
1     AB de Villiers    119.413549
2       AC Gilchrist    136.541738
3          AM Rahane    113.240418
4          AT Rayudu    121.500722
5        BB McCullum    129.081633
6           BJ Hodge    112.740741
7           CH Gayle    148.096886
8          DA Warner    131.162791
9   DPMD Jayawardene    127.740492
10         G Gambhir    120.525351
11          GC Smith    106.946454
12          HH Gibbs    107.908847
13         IK Pathan    121.578100
14         JA Morkel    140.208333
15         JH Kallis    108.055556
16         JP Duminy    113.975155
17        KA Pollard    138.671210
18     KC Sangakkara    124.612580
19        KD Karthik    126.897844
20       LRPL Taylor    131.450094
21           M Vijay    128.798842
22        MEK Hussey    121.557971
23         MK Pandey    116.575192
24         MK Tiwary    118.735632
25         ML Hayden    131.942789
26          MS Dhoni    130.331024
27           NV Ojha    115.634218
28          PA Patel    108.479532
29          R Dravid    116.965127
30         RA Jadeja    118.342391
31         RG Sharma    125.754527
32        RV Uthappa    132.722513
33       S Badrinath    120.021413
34          S Dhawan    117.694805
35        SC Ganguly    104.142582
36          SE Marsh    137.186380
37          SK Raina    136.832524
38      SR Tendulkar    114.561170
39         SR Watson    136.516129
40         SS Tiwary    117.173524
41     ST Jayasuriya    134.031414
42          TL Suman    119.411765
43        TM Dilshan    117.159763
44           V Kohli    118.439174
45          V Sehwag    163.015312
46           WP Saha    126.582278
47   Y Venugopal Rao    116.542474
48         YK Pathan    148.016277
49      Yuvraj Singh    127.497865

In [ ]:
out=ipl[ipl['player_dismissed'].isin(top50)]
nouts=out['player_dismissed'].value_counts()

avg=runs/nouts
avg=avg.reset_index()
avg.rename(columns={'index':'batsman',0:'avg'},inplace=True)

avg=avg.merge(sr,on='batsman')

In [ ]:
avg

             batsman        avg  batsman_runs
0          A Symonds  36.074074    124.711908
1     AB de Villiers  33.742857    119.413549
2       AC Gilchrist  27.169492    136.541738
3          AM Rahane  23.214286    113.240418
4          AT Rayudu  26.312500    121.500722
5        BB McCullum  29.418605    129.081633
6           BJ Hodge  31.708333    112.740741
7           CH Gayle  38.909091    148.096886
8          DA Warner  34.390244    131.162791
9   DPMD Jayawardene  31.722222    127.740492
10         G Gambhir  34.017241    120.525351
11          GC Smith  28.423077    106.946454
12          HH Gibbs  26.833333    107.908847
13         IK Pathan  23.593750    121.578100
14         JA Morkel  28.041667    140.208333
15         JH Kallis  32.416667    108.055556
16         JP Duminy  33.363636    113.975155
17        KA Pollard  22.611111    138.671210
18     KC Sangakkara  30.377778    124.612580
19        KD Karthik  28.808511    126.897844
20       LRPL Taylor  31.727273    131.450094
21           M Vijay  27.812500    128.798842
22        MEK Hussey  44.733333    121.557971
23         MK Pandey  33.187500    116.575192
24         MK Tiwary  33.322581    118.735632
25         ML Hayden  36.900000    131.942789
26          MS Dhoni  36.804348    130.331024
27           NV Ojha  22.400000    115.634218
28          PA Patel  22.714286    108.479532
29          R Dravid  27.577778    116.965127
30         RA Jadeja  28.096774    118.342391
31         RG Sharma  29.761905    125.754527
32        RV Uthappa  27.654545    132.722513
33       S Badrinath  33.969697    120.021413
34          S Dhawan  30.851064    117.694805
35        SC Ganguly  28.447368    104.142582
36          SE Marsh  47.843750    137.186380
37          SK Raina  36.967213    136.832524
38      SR Tendulkar  40.069767    114.561170
39         SR Watson  35.266667    136.516129
40         SS Tiwary  25.192308    117.173524
41     ST Jayasuriya  27.428571    134.031414
42          TL Suman  25.375000    119.411765
43        TM Dilshan  27.310345    117.159763
44           V Kohli  28.666667    118.439174
45          V Sehwag  30.755556    163.015312
46           WP Saha  27.272727    126.582278
47   Y Venugopal Rao  23.000000    116.542474
48         YK Pathan  27.452830    148.016277
49      Yuvraj Singh  26.660714    127.497865

In [ ]:
trace=go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batsman'],
                 marker={'color':'green','size':16})
data=[trace]
layout=go.Layout(title='Batsman avg vs SR',
                 xaxis={'title':'Batsman Average'},
                 yaxis={'title':'Batsman Strike'})
fig=go.Figure(data,layout)

fig.show()

In [ ]:
single=ipl[ipl['batsman']=='V Kohli']
performance=single.groupby('season')['batsman_runs'].sum().reset_index()

single1=ipl[ipl['batsman']=='MS Dhoni']
performance1=single1.groupby('season')['batsman_runs'].sum().reset_index()

In [ ]:
performance

   season  batsman_runs
0    2008         165.0
1    2009         246.0
2    2010         307.0
3    2011         522.0
4    2017         308.0

In [ ]:
trace=go.Scatter(x=performance['season'],y=performance['batsman_runs'],
                 mode="lines+markers",marker={'color':'green'},name="v kohli")

trace1=go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],
                 mode="lines+markers",marker={'color':'red'},name="MS Dhoni")


data=[trace,trace1]
leyout=go.Layout(title="Year wise performance",
                 xaxis={'title':'Season'},
                 yaxis={'title':'total runs'})

fig=go.Figure(data,layout)
fig.show()